# Generated by Django 3.1.1 on 2022-05-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(default='RED', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='current_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node', to='Tata.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='progress_label',
            field=models.CharField(default='At Risk', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
